include("${LITERTLM_MODULES_DIR}/utils.cmake")
include("${LITERTLM_ABSL_CONFIG_PATH}")
include("${LITERTLM_RE2_CONFIG_PATH}")

set(absl_DIR "${LITERTLM_ABSL_INSTALL_PREFIX}/lib/cmake/absl" CACHE PATH "Path to absl config")
set(ABSL_DIR "${LITERTLM_ABSL_INSTALL_PREFIX}/lib/cmake/absl" CACHE PATH "Path to absl config")
set(absl_ROOT "${LITERTLM_ABSL_INSTALL_PREFIX}" CACHE PATH "absl root dir")
set(ABSL_ROOT "${LITERTLM_ABSL_INSTALL_PREFIX}" CACHE PATH "absl root dir")

set(ABSL_INCLUDE_DIR "${LITERTLM_ABSL_INSTALL_PREFIX}/include" CACHE PATH "absl include dir")
set(ABSL_INCLUDE_DIRS "${LITERTLM_ABSL_INSTALL_PREFIX}/include" CACHE PATH "absl include dirs")
set(absl_INCLUDE_DIR "${LITERTLM_ABSL_INSTALL_PREFIX}/include" CACHE PATH "absl include dir")
set(absl_INCLUDE_DIRS "${LITERTLM_ABSL_INSTALL_PREFIX}/include" CACHE PATH "absl include dirs")
set(ABSL_LIBRARY_DIR "${LITERTLM_ABSL_INSTALL_PREFIX}/lib" CACHE PATH "absl lib dir")
set(ABSL_LIB_DIR "${LITERTLM_ABSL_INSTALL_PREFIX}/lib" CACHE PATH "absl lib dir")
set(absl_LIBRARY_DIR "${LITERTLM_ABSL_INSTALL_PREFIX}/lib" CACHE PATH "absl lib dir")


list(APPEND CMAKE_PREFIX_PATH "${LITERTLM_ABSL_INSTALL_PREFIX}")
list(APPEND CMAKE_SYSTEM_PREFIX_PATH "${LITERTLM_ABSL_INSTALL_PREFIX}")