set(LITERTLM_RE2_EXT_PREFIX "${LITERTLM_EXTERNAL_PROJECT_BIN_DIR}/re2" CACHE PATH "")
set(LITERTLM_RE2_INSTALL_PREFIX "${LITERTLM_RE2_EXT_PREFIX}/install" CACHE PATH "")
set(LITERTLM_RE2_CONFIG_PATH "${LITERTLM_RE2_PACKAGE_DIR}/re2_config.cmake" CACHE PATH "")
set(LITERTLM_RE2_SRC_DIR "${LITERTLM_RE2_EXT_PREFIX}/src/re2_external" CACHE PATH "")
set(LITERTLM_RE2_LIB_DIR "${LITERTLM_RE2_INSTALL_PREFIX}/lib" CACHE PATH "")
set(LITERTLM_RE2_BIN_DIR "${LITERTLM_RE2_INSTALL_PREFIX}/bin" CACHE PATH "")
set(LITERTLM_RE2_INCLUDE_DIR "${LITERTLM_RE2_INSTALL_PREFIX}/include" CACHE PATH "")
set(LITERTLM_RE2_SHIM_PATH "${LITERTLM_RE2_PACKAGE_DIR}/re2_shim.cmake" CACHE PATH "")
set(LITERTLM_RE2_AGGREGATE_PATH "${LITERTLM_RE2_PACKAGE_DIR}/re2_aggregate.cmake" CACHE PATH "")
set(LITERTLM_RE2_PACKAGE_DIR
    "${LITERTLM_CMAKE_PACKAGES_DIR}/re2"
    CACHE PATH "Path to RE2 related build scripts")