# Copyright 2026 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


set(LITERTLM_SENTENCEPIECE_CONFIG_PATH "${LITERTLM_SENTENCEPIECE_PACKAGE_DIR}/sentencepiece_config.cmake")
include("${LITERTLM_SENTENCEPIECE_CONFIG_PATH}")
include("${LITERTLM_ABSL_CONFIG_PATH}")
include("${LITERTLM_PROTOBUF_CONFIG_PATH}")


include(ExternalProject)
setup_external_install_structure("${LITERTLM_SENTENCEPIECE_INSTALL_PREFIX}")

  ExternalProject_Add(
    sentencepiece_external
    DEPENDS
      absl_external
      protobuf_external
    GIT_REPOSITORY https://github.com/google/sentencepiece.git
    GIT_TAG        v0.2.2
    PREFIX         ${LITERTLM_SENTENCEPIECE_EXT_PREFIX}

    PATCH_COMMAND
      git checkout -- . && git clean -df
      COMMAND ${CMAKE_COMMAND}
      "-DLITERTLM_EXTERNAL_PROJECT_BIN_DIR=${LITERTLM_EXTERNAL_PROJECT_BIN_DIR}"
      "-DLITERTLM_MODULES_DIR=${LITERTLM_MODULES_DIR}"
      "-DLITERTLM_CMAKE_PACKAGES_DIR=${LITERTLM_CMAKE_PACKAGES_DIR}"
      "-DLITERTLM_SENTENCEPIECE_PACKAGE_DIR=${LITERTLM_SENTENCEPIECE_PACKAGE_DIR}"
      "-DLITERTLM_SENTENCEPIECE_CONFIG_PATH=${LITERTLM_SENTENCEPIECE_CONFIG_PATH}"
      "-DLITERTLM_ABSL_PACKAGE_DIR=${LITERTLM_ABSL_PACKAGE_DIR}"
      "-DLITERTLM_ABSL_CONFIG_PATH=${LITERTLM_ABSL_CONFIG_PATH}"
      "-DLITERTLM_PROTOBUF_PACKAGE_DIR=${LITERTLM_PROTOBUF_PACKAGE_DIR}"
      "-DLITERTLM_PROTOBUF_CONFIG_PATH=${LITERTLM_PROTOBUF_CONFIG_PATH}"
      "-DLITERTLM_HOST_PROTOC_BIN_DIR=${LITERTLM_HOST_PROTOC_BIN_DIR}"
      "-DLITERTLM_HOST_PROTOC=${LITERTLM_HOST_PROTOC}"
      "-P ${LITERTLM_SENTENCEPIECE_PACKAGE_DIR}/sentencepiece_patcher.cmake"

    CMAKE_ARGS
      ${LITERTLM_TOOLCHAIN_FILE}
      ${LITERTLM_TOOLCHAIN_ARGS}
      "-DLITERTLM_ORCHESTRATION_PHASE=${LITERTLM_ORCHESTRATION_PHASE}"
      "-DLITERTLM_EXTERNAL_PROJECT_BIN_DIR=${LITERTLM_EXTERNAL_PROJECT_BIN_DIR}"
      "-DLITERTLM_MODULES_DIR=${LITERTLM_MODULES_DIR}"
      "-DLITERTLM_CMAKE_PACKAGES_DIR=${LITERTLM_CMAKE_PACKAGES_DIR}"
      "-DLITERTLM_SENTENCEPIECE_PACKAGE_DIR=${LITERTLM_SENTENCEPIECE_PACKAGE_DIR}"
      "-DLITERTLM_SENTENCEPIECE_CONFIG_PATH=${LITERTLM_SENTENCEPIECE_CONFIG_PATH}"
      "-DLITERTLM_ABSL_PACKAGE_DIR=${LITERTLM_ABSL_PACKAGE_DIR}"
      "-DLITERTLM_ABSL_CONFIG_PATH=${LITERTLM_ABSL_CONFIG_PATH}"
      "-DLITERTLM_PROTOBUF_PACKAGE_DIR=${LITERTLM_PROTOBUF_PACKAGE_DIR}"
      "-DLITERTLM_PROTOBUF_CONFIG_PATH=${LITERTLM_PROTOBUF_CONFIG_PATH}"
      "-DLITERTLM_HOST_PROTOC_BIN_DIR=${LITERTLM_HOST_PROTOC_BIN_DIR}"
      "-DLITERTLM_HOST_PROTOC=${LITERTLM_HOST_PROTOC}"

      "-DCMAKE_INSTALL_PREFIX=${LITERTLM_SENTENCEPIECE_INSTALL_PREFIX}"
      "-DCMAKE_INSTALL_LIBDIR=lib"
      "-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
      "-DCMAKE_POLICY_VERSION_MINIMUM=3.5"
      "-DCMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD}"
      "-DCMAKE_CXX_STANDARD_REQUIRED=ON"
      "-DCMAKE_POSITION_INDEPENDENT_CODE=ON"
      "-DCMAKE_PREFIX_PATH=${LITERTLM_ABSL_INSTALL_PREFIX};${LITERTLM_PROTOBUF_INSTALL_PREFIX}"

      "-DSPM_ABSL_PROVIDER=package"
      "-DSPM_PROTOBUF_PROVIDER=package"
      "-DSPM_ENABLE_SHARED=OFF"
      "-DSPM_ENABLE_TCMALLOC=OFF"

      "-Dabsl_DIR=${LITERTLM_ABSL_INSTALL_PREFIX}/lib/cmake/absl"
      "-DABSL_INCLUDE_DIRS=${LITERTLM_ABSL_INCLUDE_DIR}"
      "-DABSL_INCLUDE_DIR=${LITERTLM_ABSL_INCLUDE_DIR}"
      "-DABSL_SRC_DIR=${LITERTLM_ABSL_SRC_DIR}"
      "-DABSL_LIB_DIR=${LITERTLM_ABSL_LIB_DIR}"
      "-DABSL_PACKAGE_DIR=${LITERTLM_ABSL_PACKAGE_DIR}"

      "-DProtobuf_DIR=${LITERTLM_PROTOBUF_INSTALL_PREFIX}/lib/cmake/protobuf"
      "-DProtobuf_LIBRARIES=${LITERTLM_PROTOBUF_LIB_DIR}"
      "-DProtobuf_INCLUDE_DIR=${LITERTLM_PROTOBUF_INCLUDE_DIR}"
      "-DProtobuf_PROTOC_EXECUTABLE=${LITERTLM_PROTOBUF_PROTOC_EXECUTABLE}"
      "-DProtobuf_LITE_LIBRARY=${LITERTLM_PROTOBUF_LIB_DIR}/libprotobuf.a"
      "-DProtobuf_PROTOC_LIBRARY_DEBUG=${LITERTLM_PROTOBUF_LIB_DIR}/libprotoc.a"
      "-DProtobuf_PROTOC_LIBRARY_RELEASE=${LITERTLM_PROTOBUF_LIB_DIR}/libprotoc.a"
      "-DPROTO_PROTOC_EXECUTABLE=${LITERTLM_PROTOC_EXECUTABLE}"
      "-DPROTO_INCLUDE_DIR=${LITERTLM_PROTOBUF_INCLUDE_DIR}"
      "-DPROTOBUF_PACKAGE_DIR=${LITERTLM_PROTOBUF_PACKAGE_DIR}"
      "-DPROTO_LIB_DIR=${LITERTLM_PROTOBUF_LIB_DIR}"
      "-DPROTO_SRC_DIR=${LITERTLM_PROTOBUF_SRC_DIR}"

  )
  if(NOT TARGET sentencepiece_external)
    add_custom_target(sentencepiece_external)
  endif()

include("${LITERTLM_SENTENCEPIECE_PACKAGE_DIR}/sentencepiece_aggregate.cmake")
generate_sentencepiece_aggregate()
