set(LITERTLM_GTEST_EXT_PREFIX "${LITERTLM_EXTERNAL_PROJECT_BIN_DIR}/googletest" CACHE PATH "")
set(LITERTLM_GTEST_SRC_DIR "${LITERTLM_GTEST_EXT_PREFIX}/src" CACHE INTERNAL "")
set(LITERTLM_GTEST_STAMP_DIR "${LITERTLM_GTEST_EXT_PREFIX}/src/gtest_external-stamp" CACHE INTERNAL "")
set(LITERTLM_GTEST_INSTALL_PREFIX "${LITERTLM_GTEST_EXT_PREFIX}/install" CACHE PATH "")
set(LITERTLM_GTEST_INCLUDE_DIR "${LITERTLM_GTEST_INSTALL_PREFIX}/include" CACHE PATH "")
set(LITERTLM_GTEST_CONFIG_CMAKE_FILE "${LITERTLM_GTEST_INSTALL_PREFIX}/lib/cmake/GTest/GTestConfig.cmake"  CACHE PATH "")
set(LITERTLM_GTEST_PACKAGE_DIR
    "${LITERTLM_CMAKE_PACKAGES_DIR}/gtest"
    CACHE PATH "Path to gtest related build scripts")